### ISSUE TITLE
broken, missing, or mislabeled link

### ISSUE THREAD

**Issue by musicnerd** [Computational-Cognitive-Musicology-Lab/humdrumR#14]
In the rhythm and meter vignette (https://computational-cognitive-musicology-lab.github.io/humdrumR/articles/RhythmAndMeter.html) there is a line that states:
"The global documentation for all the rhythm functions can be seen by calling [?rhythmFunctions](https://computational-cognitive-musicology-lab.github.io/humdrumR/reference/rhythmFunctions.html)." 

This links to a page that is (a) incorrectly titled "manipulate Pitch data", and 
(b) only contains minimal docs for 'recip' and 'duration' functions but none of the other functions listed on this main 'RhythmAndMeter' page (e.g., ms, seconds, dur, quarters, etc.)

Is this the correct link and it simply is incomplete (and mislabeled?) or is there another link?

**Comment by natsguitar** [comment]
It looks like this has already been fixed my updates to the docs.
