### ISSUE TITLE
Parsing a valid kern file from the JRP fails with `Error in mat[, 1] : subscript out of bounds` 

### ISSUE THREAD

**Issue by johentsch** [Computational-Cognitive-Musicology-Lab/humdrumR#19]
**To reproduce:**

Download https://raw.githubusercontent.com/josquin-research-project/Jos/main/Jos0703b-Missa_Dung_aultre_amer-Gloria.krn 

<details>
<summary>maybe in a future version</summary> 

```R
readHumdrum(url("https://raw.githubusercontent.com/josquin-research-project/Jos/main/Jos0703b-Missa_Dung_aultre_amer-Gloria.krn"))`)
```
</details>

```R
readHumdrum("~/Jos0703b-Missa_Dung_aultre_amer-Gloria.krn")
```

**Unexpected behaviour:**

Error `Parsing one files...Error in mat[, 1] : subscript out of bounds`

<details><summary>Stacktrace</summary>

```R
7: parseSections(mat[, 1])
6: parseLocal(records)
5: parseRecords(file, piece, reference)
4: (function (file, piece) 
   {
       humtab <- parseRecords(file, piece, reference)
       if (verbose) 
           message(file, "\n")
       humtab
   })(dots[[1L]][[2L]], dots[[2L]][[2L]])
3: mapply(FUN = f, ..., SIMPLIFY = FALSE)
2: Map(function(file, piece) {
       humtab <- parseRecords(file, piece, reference)
       if (verbose) 
           message(file, "\n")
       humtab
   }, fileFrame$FileLines, fileFrame$Piece)
1: readHumdrum("~/Jos0703b-Missa_Dung_aultre_amer-Gloria.krn")
```
</details>

**Inspection:**

The code fails at [this line](https://github.com/Computational-Cognitive-Musicology-Lab/humdrumR/blob/90475a06550b671b87c2fe6fed8215ec9f8ab894/R/Read.R#L856) when the function `parseLocal` is called with `records` corresponding to lines 278-295 of the Gloria, which results in all local variables to be empty, including `mat`:

```
!!!RDF**kern: Z=end of tuplet marker 
!!!ENC: Jesse Rodin 2012/02/27 
!!!END: 2012/02/27/ 
!!!EED: Jesse Rodin 
!!!EEV: 2012/03/22/ 
!!attribution-level@Jos: 2 (provisionally attributable [parentheses checkmark]) 
!!!ONB: Translated from MusicXML and edited on 2012/03/22/ by Craig Sapp 
!!muse2ps: T^@{OPR}^u^@{ONM}{. }@{OTL}^C^@{COM}^i2I150v90,90,90,120c122z18l2700t130 
!!!COM: Josquin des Prez 
!!!CDT: ~1450-1521/08/27 
!!!OPR: Missa D'ung aultre amer--Tu solus 
!!!ONM: 2 
!!!OTL: Gloria 
!!!AGN: Mass; Gloria; Missa Brevis 
!!!SCT: NJE 7.3 
!!!SCA: New Josquin Edition 7.3 
!!!voices: 4 
!!!voices-OPR: 4 
```

**Comment by natsguitar** [comment]
Sorry for the delay.

I've found and fixed the bug that causes this (thanks for pointing me in the right direction). However, you've also stumbled onto a bigger blind spot I have. I rarely work with files where there are multiple pieces within the same file. (I.e., places where all the spines close and then you get another record of exclusive interpretations.)

humdrumR includes a distinction between the "File" and the "Piece", but many many functions are (by default) using File not Piece. I will need to change "File" to "Piece" in a bunch of places, and hope that I don't break anything in the process.

**Comment by johentsch** [comment]
Yes, it complicates things that so krn-files have metadata above and below the spines, in particular with several pieces encoded in the same file. Thanks for addressing this.

**Comment by natsguitar** [comment]
I just pushed humdrumR 6.2.0, which properly reads your file and works better with multi-piece files.

The problem of reference records that appear before AND after files is tricky. I don't see a good way for humdrumR to automatically know which reference records to associate with each file. The only  approach I see would be to have humdrumR to assume that a repeated reference record after *- is a new file. Do you have a suggestion?

**Comment by natsguitar** [comment]
Ok. This is not totally trivial, because technically you can have duplicated reference records. For example, a piece written as a collaboration between two composers can have two !!!COM records. However, I've implemented an algorithm (in the separatePieces() function) which attempts to allocate reference records in multi-piece files by avoiding duplicates where possible. This will be pushed with the latest version of humdrumR, hopefully later today.
