### ISSUE TITLE
Print file parsing issues to console

### ISSUE THREAD

**Issue by musicnerd** [Computational-Cognitive-Musicology-Lab/humdrumR#20]
In addition to printing the log files, can we print errors directly to console for files that fail to read using the 'readHumdrum()' function?

**Comment by natsguitar** [comment]
Yes, validateHumdrum() actually already does this, but "invisibly", which means you have to save the output to a variable before you can see it.

For example, you can run `errors <- validateHumdrum(...)` and then print `errors`.

I'm making some tweaks to make the error output easier to read though! These will appear in the next version.
