### ISSUE TITLE
timebase bug?

### ISSUE THREAD

**Issue by musicnerd** [Computational-Cognitive-Musicology-Lab/humdrumR#32]
Calling timebase gives unusual error (see screenshot)

![Screen Shot 2024-09-19 at 8 59 13 AM](https://github.com/user-attachments/assets/49c3235f-66f8-4862-8bba-162941c4d399)

**Comment by natsguitar** [comment]
I fixed the bug which is causing this error message, but it seems that `timebase()` really just isn't working yet. I'll have to take a look at it.

Also, `timebase()` (once it works) will only work applied directly to a humdrumR object, not using `mutate()` or `within()`. So you will write `chors |> timebase(tb = '32')`.

It's a moot point until I get it working though!
