### ISSUE TITLE
man pages for all functions

### ISSUE THREAD

**Issue by musicnerd** [Computational-Cognitive-Musicology-Lab/humdrumR#6]
E.g., "mint" is subsumed within "intervals" (https://computational-cognitive-musicology-lab.github.io/humdrumR/reference/int.html). In addition, the man pages for each function should include sample code. 

A quick search for any pandas or numpy function will give an ideal example of the design here.

**Comment by natsguitar** [comment]
In R, very similar or related functions are usually put in the same man page. In the example you give, int(), mint(), and hint() are in the same man page. This is intentional, because it makes a lot less duplication between man pages.
