### ISSUE TITLE
How to use partial pitch functions?

### ISSUE THREAD

**Issue by SileYin** [Computational-Cognitive-Musicology-Lab/humdrumR#7]
As the title suggests, partial pitch functions such as `accidental()`, `octave()`, `step()`, and `quality()` have no documentation at all and I have no idea how to use these.

**Comment by natsguitar** [comment]
The idea is that they will work just like kern(), or pitch(), except they only return either accidental/quality, step, or octave. For now they aren't really working...I know why, and can fix them, but its not a priority right this second.

**Comment by natsguitar** [comment]
I'm fixing the bugs in these and have added to the documentation about them.
